### PR TITLE
[WIP] Rewrite the whole operating system

### PR DESCRIPTION
**Pull request by sinjs**
The current structure is a mess. So I decided to create a full rewrite of the operating system!

**TODOs:**
- [ ] Make it work on real hardware
- [ ] Make it easier to build
- [ ] Implement User Interface
- [ ] User input
- [ ] Networking
- [ ] Browser
- [ ] ELF Parsing
- [ ] File system (FAT32 or EXT4)
...and much more

I would really love some help with this.

### CODE REVIEW

**Comment by aeroplaneticdos** [comment]
**oh my god**

**Comment by sinjs** [comment]
> **oh my god**

@aquaticdosDev 

HELP ME THEN

**Comment by aeroplaneticdos** [comment]
> > **oh my god**
> 
> @aquaticdosDev
> 
> HELP ME THEN

~~NEVER~~ yes uwu

**Comment by sinjs** [comment]
you are a bad person :(

wait bro what the fuck

**Review by viermat — APPROVED** [review]
why is test-app/sources/main.c literally c started code

**Comment by sinjs** [comment]
> why is test-app/sources/main.c literally c started code

because it literally is a test app for the goddam os

**Comment by sinjs** [comment]
This is unstable anyways so I can merge it

**Comment by aeroplaneticdos** [comment]
> > > **oh my god**
> > 
> > 
> > @aquaticdosDev
> > HELP ME THEN
> 
> ~NEVER~ yes uwu

sin what the fuck did you just edit it to

**Comment by sinjs** [comment]
wasn't me

**Pull request merged**
